#:schema node_modules/wrangler/config-schema.json
name = "chuo-ids-iioseminar-data-gather-backend"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "CIDG_DATABASE"
database_id = "cc010370-df95-4f15-9096-a6d24938c2ed"
