openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /:
    get:
      description: 投稿一覧を見ることができる
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        email:
                          type: string
                        name:
                          type: string
                        message:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
  /post:
    post:
      description: 投稿を行うことができる
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
                      message:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
